### ISSUE TITLE
Allow selecting one day of recordings for batch download

### ISSUE THREAD

**Issue by atruskie** [Allcharles/workbench-client#1927]
User tried to select one day of recordings to download.

With one day range: 0 results
With two days range:  two-days worth.

This is likely a bug our end exclusion constraint that required some trickery because arrays of conditions were not supported for filter queries (https://github.com/QutEcoacoustics/baw-server/issues/567)

**Comment by hudson-newey** [comment]
I have been able to reproduce this bug in Postman for an audio recording on the `17/06/2022`, suggesting this might be a server side issue. From experimenting around for a short while, it seems to be an issue originating from the `gteq` operator being treated as a `>` operator. Possibly because the.

**Bug reproduced in Postman**
![image](https://user-images.githubusercontent.com/33742269/216856622-01e75be4-0b0f-4877-9254-977a2e9f830f.png)

**Proof that the file exists**
![image](https://user-images.githubusercontent.com/33742269/216856633-a742f73e-f7e8-45e4-a9d5-36c7cef103fa.png)

_With date `>= 16/06/2022` (one day before audio recording) - `<= 17/06/2022` (audio recording date), showing that the `<=` operator is working correctly_

**Evidence to support the idea that the `>=` operator is being treated as `>`:**
![image](https://user-images.githubusercontent.com/33742269/216856688-42457bca-343a-498a-818d-60a13af23e69.png)

_Evidence photo includes date `>= 17/06/2022` - `<= 18/06/2022`, showing that even though the date should be equal to `17/06/2022`, it is not showing in the returned results_

**Comment by atruskie** [comment]
Ok; so, while I never assume code is bug free, I am going to tell you that it is highly unlikely that that the operator is wrong on in the filtering code.

Evidence: https://github.com/QutEcoacoustics/baw-server/blob/b5a9f807d67a414610c665a499f39d50aa37d423/app/modules/filter/comparison.rb#L87-L95

Compare against the other functions in that file; you'll see that they're consistent.

---

Side note: the API isn't fussy about it currently, but it should be considered an error to send a date-only time stamp. `2022-06-17` is a partial date. Always send the full form `2022-06-17T00:00:00`.

---


So why is this occurring?

Well, your conditions are incorrect, I think. In the first example you effectively have:

```
recorded_date >= '2022-06-17T00:00:00'  && recorded_end_date <= '2022-06-17T00:00:00'  
```

The only possible recording that could satisfy that logic is a recording that started at '2022-06-17T00:00:00'   and that was 0 seconds long!

We need to rethink the logic of the filter sent to the server. https://github.com/QutEcoacoustics/baw-server/wiki/API:-Filtering#filtering-by-time-of-day

**Comment by hudson-newey** [comment]
Aha, that makes a lot of sense, I'll verify, create a client patch, and create some tests to ensure this but doesn't resurface.
