### ISSUE TITLE
Bulk download: provide advice for linux or maxos users to launch pwsh from terminal/bash

### ISSUE THREAD

**Issue by atruskie** [Allcharles/workbench-client#1931]
From user testing: our current guide for launching a terminal in the current folder is working well for macs, however, it does not cover stating powershell afterwards.

If we just add "type `pwsh` and press <kbd>Enter</kbd>" as another step the workflow will be complete

**Comment by hudson-newey** [comment]
It may be worth while extending the scope of this ticket to redesign the steps to have tabs per operating system, similar to how the batch uploading component works. It may not bring a significant improvement since there are only 2 steps differing from the Windows steps and it'd add more complexity, but it might be a worth while consideration as there won't be as many "if, then follow this bullet point".

**Current Layout:**
![image](https://user-images.githubusercontent.com/33742269/210309044-d0934dd5-4bf1-4656-99a3-e4840d078657.png)

**Proposed similar layout:**
![image](https://user-images.githubusercontent.com/33742269/210309073-e0fca104-0e1a-46fe-9dfd-952c05deb6d9.png)

**Edit: This is probably overkill since we only need to support 2 user groups (Windows & MacOS/Linux)**
