### ISSUE TITLE
Harvest: Upload screen UI tweaks

### ISSUE THREAD

**Issue by atruskie** [Allcharles/workbench-client#1968]
On the Harvest upload screen make the following changes:

- [ ] Point out on "Upload your data" card that _You can assign a point/site to any folder later on_

![Image](https://user-images.githubusercontent.com/1452968/181685349-3b9da97f-cb6d-4f74-b861-e224302500d7.png)

- [ ] Change the card grid to 2x2
- [ ] Add advice to set WinSCP to background transfer by default

![image](https://user-images.githubusercontent.com/1452968/181688108-a2c51c9c-02e2-432c-966c-f5f920eb2061.png)

**Comment by hudson-newey** [comment]
I have created a mock up for the changes requested in this ticket. The optional change I have considered is instead of linking to a wiki article in the `guide` link, we describe it through navigation descriptors e.g.

Options > Preferences > Background > "Transfer on background by default"

However, this would not fit with the style used above, were each menu item is listed in a separate menu item.

![image](https://user-images.githubusercontent.com/33742269/210286456-f1ce9607-4f1a-4b1c-a1d5-ce62fa51073b.png)

**Comment by hudson-newey** [comment]
I have created a mock-up of the requested UI changes. The only change I considered was instead of using a wiki article to show the user how to set "Transfer on background by default", use descriptors e.g.
Options > Preferences > Background > "Transfer on background by default"

![image](https://user-images.githubusercontent.com/33742269/210286718-6ea7053b-7afb-4174-8349-7eb3f8796cda.png)
