### ISSUE TITLE
Improve performance of the harvest list page

### ISSUE THREAD

**Issue by atruskie** [Allcharles/workbench-client#2045]
**Is your feature request related to a problem? Please describe.**

Loading the harvest list page can take a long time. For the A2O it looks like two requests are made:

![image](https://user-images.githubusercontent.com/1452968/223281005-dd79d83f-2a23-453f-b0ca-a708f99d5e45.png)

6 seconds is really very slow.

**Describe the solution you'd like**

- [x] Work out why two requests are sent
- [x] Only load partial objects. Use the filter options to exclude properties from the API response that aren't needed and are costly to send/calculate (like `mappings` and `report`)
- [ ] Measure performance is actually improved with the above suggestions
    - if not we may have to change something on the server

**Comment by hudson-newey** [comment]
This might be caused by the `[bawDatatablePagination]` directive as I'm also seeing this behavior on all the datatables that use the directive (harvest list page, project permissions page, and batch download page).

I've also verified that the `getModels()` method is firing twice using a dirty `console.log` hack whenever it's called
![image](https://github.com/QutEcoacoustics/workbench-client/assets/33742269/47fae04e-bc09-486e-975a-b35b3a79cc95)
